/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAiScoringRouteImport } from './routes/_authenticated/ai-scoring'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated/companies.$id'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiScoringRoute = AuthenticatedAiScoringRouteImport.update({
  id: '/ai-scoring',
  path: '/ai-scoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-scoring': typeof AuthenticatedAiScoringRoute
  '/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-scoring': typeof AuthenticatedAiScoringRoute
  '/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/ai-scoring': typeof AuthenticatedAiScoringRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/ai-scoring'
    | '/assets'
    | '/companies'
    | '/dashboard'
    | '/maintenance'
    | '/pipeline'
    | '/quotations'
    | '/assets/$id'
    | '/companies/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/ai-scoring'
    | '/assets'
    | '/companies'
    | '/dashboard'
    | '/maintenance'
    | '/pipeline'
    | '/quotations'
    | '/assets/$id'
    | '/companies/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/ai-scoring'
    | '/_authenticated/assets'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/maintenance'
    | '/_authenticated/pipeline'
    | '/_authenticated/quotations'
    | '/_authenticated/assets/$id'
    | '/_authenticated/companies/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-scoring': {
      id: '/_authenticated/ai-scoring'
      path: '/ai-scoring'
      fullPath: '/ai-scoring'
      preLoaderRoute: typeof AuthenticatedAiScoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedAssetsRoute
    }
  }
}

interface AuthenticatedAssetsRouteChildren {
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
}

const AuthenticatedAssetsRouteChildren: AuthenticatedAssetsRouteChildren = {
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
}

const AuthenticatedAssetsRouteWithChildren =
  AuthenticatedAssetsRoute._addFileChildren(AuthenticatedAssetsRouteChildren)

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiScoringRoute: typeof AuthenticatedAiScoringRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRouteWithChildren
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiScoringRoute: AuthenticatedAiScoringRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRouteWithChildren,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
